function colorChangeBlack(){
    document.body.style.backgroundColor="#1C1C1C";
    document.getElementById("header").style.backgroundColor="#1e121c";
    document.getElementById("home-button").style.color="white";
    document.getElementById("about-button").style.color="white";
    document.getElementById("forum-button").style.color="white";
    document.getElementById("PH").style.color="white";
    document.getElementById("Sunday").style.color="white";
    document.getElementById("Monday").style.color="white";
    document.getElementById("Tuesday").style.color="white";
    document.getElementById("Wednesdays").style.color="white";
    document.getElementById("Thursday").style.color="white";
    document.getElementById("Friday").style.color="white";
    document.getElementById("Saturday").style.color="white";
    document.a.style.color="white"
    document.p.style.color="white"
    document.h2.style.color="white"
    document.getElementById("animeReview4").style.color="white"
}
function colorChangeBlue(){
    document.body.style.backgroundColor="#58D3F7";
    document.getElementById("header").style.backgroundColor="#01A9DB";
    document.getElementById("home-button").style.color="#000000";
    document.getElementById("about-button").style.color="#000000";
    document.getElementById("forum-button").style.color="#000000";
    document.getElementById("PH").style.color="#000000";
    document.getElementById("Sunday").style.color="#000000";
    document.getElementById("Monday").style.color="#000000";
    document.getElementById("Tuesday").style.color="#000000";
    document.getElementById("Wednesdays").style.color="#000000";
    document.getElementById("Thursday").style.color="#000000";
    document.getElementById("Friday").style.color="#000000";
    document.getElementById("Saturday").style.color="#000000";
    document.getElementById("animeReview1").style.color="#000000"
    document.getElementById("animeReview2").style.color="#000000"
    document.getElementById("animeReview3").style.color="#000000"
    document.getElementById("animeReview4").style.color="#000000"
}
function colorChangePink(){
    document.body.style.backgroundColor="#f2e1c6";
    document.getElementById("header").style.backgroundColor="#f9ae9b";
    document.getElementById("home-button").style.color="#000000";
    document.getElementById("about-button").style.color="#000000";
    document.getElementById("forum-button").style.color="#000000";
    document.getElementById("PH").style.color="#000000";
    document.getElementById("Sunday").style.color="#000000";
    document.getElementById("Monday").style.color="#000000";
    document.getElementById("Tuesday").style.color="#000000";
    document.getElementById("Wednesdays").style.color="#000000";
    document.getElementById("Thursday").style.color="#000000";
    document.getElementById("Friday").style.color="#000000";
    document.getElementById("Saturday").style.color="#000000";
    document.getElementById("animeReview1").style.color="#000000"
    document.getElementById("animeReview2").style.color="#000000"
    document.getElementById("animeReview3").style.color="#000000"
    document.getElementById("animeReview4").style.color="#000000"
}
function colorChangeGreen(){
    document.body.style.backgroundColor="#82FA58";
    document.getElementById("header").style.backgroundColor="#3ADF00";
    document.getElementById("home-button").style.color="#000000";
    document.getElementById("about-button").style.color="#000000";
    document.getElementById("forum-button").style.color="#000000";
    document.getElementById("PH").style.color="#000000";
    document.getElementById("Sunday").style.color="#000000";
    document.getElementById("Monday").style.color="#000000";
    document.getElementById("Tuesday").style.color="#000000";
    document.getElementById("Wednesdays").style.color="#000000";
    document.getElementById("Thursday").style.color="#000000";
    document.getElementById("Friday").style.color="#000000";
    document.getElementById("Saturday").style.color="#000000";
    document.getElementById("animeReview1").style.color="#000000"
    document.getElementById("animeReview2").style.color="#000000"
    document.getElementById("animeReview3").style.color="#000000"
    document.getElementById("animeReview4").style.color="#000000"
}
